//==================================================
//     Outputs that match the input variables
//==================================================
output "error_message" {
  description = "The value of the `error_message` input variable."
  value       = var.error_message
}

output "condition" {
  description = "The value of the `condition` input variable."
  value       = var.condition
}

output "assertions" {
  description = "The value of the `assertions` input variable."
  value       = var.assertions
}

//==================================================
//       Outputs generated by this module
//==================================================
output "checked" {
  description = "Whether the condition has been checked (used for assertion dependencies)."
  value       = nonsensitive(nonsensitive(var.condition) == true ? true : true)
}
